### ISSUE TITLE
stronger camera mounts

### ISSUE THREAD

**Issue by geezacoleman** [geezacoleman/OpenWeedLocator#11]
Issues with camera mount breaking/weaknesses have become clear. Need a redesign of the mounting hardware to make it sturdier and potentially shorter to fit on smaller print plates.

**Comment by williamtsalter** [comment]
I have now printed several updated enclosures that use standoffs to hold the HQ camera in place. These are considerably more robust than the original design. I will have to get some new photos for the hardware assembly instructions in the readme and update the 3d print files. I will do this later this week then close this issue.

**Comment by williamtsalter** [comment]
I have now updated the read me and the stl files with the stronger camera mount
