### ISSUE TITLE
Boot item

### ISSUE THREAD

**Issue by zerosnsa** [geezacoleman/OpenWeedLocator#113]
Hello, I would like to ask if I need to modify the startup item when I use Green-on-Green, or do I not need to?

**Comment by geezacoleman** [comment]
You won't need to change anything on the booting side, just the default setting of lines 521 - 522 of `owl.py`:

```python
ap.add_argument('--algorithm', type=str, default='gog', choices=['exg', 'nexg', 'exgr', 'maxg', 'exhsv', 'hsv', 'gog'])
ap.add_argument('--model-path', type=str, default='path_to_you_model', help='path to trained weed detection .tflite model or directory')
```

I realise it's quite a clunky/bad way of doing it currently, but the plan is to migrate to [`openweedlocator-tools`](https://pypi.org/project/openweedlocator-tools/0.0.1/) package this year, which will move all these settings into a `config.json` file you can more easily edit.

**Comment by zerosnsa** [comment]
Hello, why do I want to do an operation to modify the sequence of the nozzle? Why does he show that there is no print after I make a judgment
![1706079232129](https://github.com/geezacoleman/OpenWeedLocator/assets/152005489/08b0d04e-80e1-401e-87fd-65f3a7e14631)

**Comment by geezacoleman** [comment]
Closing this as completed - feel free to reopen of needed.
