### ISSUE TITLE
Not a issue but I made a custom chat gpt 

### ISSUE THREAD

**Issue by bassyboi** [geezacoleman/OpenWeedLocator#149]
Here is a link to the chat gpt https://chatgpt.com/g/g-AZC2yEnnW-code-owl

also if you have suggestion or ideas please let me know so I can add it in

**Comment by geezacoleman** [comment]
This is awesome - thanks for developing it. It does seem to provide a lot of errors in responses around the code base though. It's a good idea for more interactive help however.

**Comment by bassyboi** [comment]
Yeah I’d need to add that all into it still
