### ISSUE TITLE
Future development 

### ISSUE THREAD

**Issue by bassyboi** [geezacoleman/OpenWeedLocator#150]
Was having an idea about maybe saving gps location of let’s say where it sprays eg section of boom sprays saves location of where it sprays putting it through gps maybe like open source gps and making a map for a pre emergent spray map? I know it’s far fetched for now but could be a game changer for saving money on the farm?? Just a thought

**Comment by geezacoleman** [comment]
Integrating GPS is on the cards (has been for a while!) but lower down the priority list. Pulling NMEA strings from the tractor GPS is probably the best way to do it.

There are companies doing predictive spraying (like Geco in Canada) based on exactly this. It's very valuable information!
