### ISSUE TITLE
I want to replace the sprayer with laser 

### ISSUE THREAD

**Issue by rajankarthiks** [geezacoleman/OpenWeedLocator#156]
I want to just use the owl for detecting the weeds and to power a laser instead of spraying. I want to use the software, please guide

**Comment by geezacoleman** [comment]
This would be a very cool idea! If you're simply turning a laser on and off then you should need to change anything on the OWL end, you'll just need to make sure your laser driver will accept either the 12V switched output from the OWL as a signal, or work directly off the GPIO pins.

Targeting a laser with galvanometers would be much more complex however. That requires much more precise awareness of where the weed is in the image in 3D space.

Just always make sure to wear appropriate laser safety gear when working with them.

Not sure if this answers your question or not, but let me know if you have any follow ups.
