### ISSUE TITLE
Bug: `input_file_or_directory` Field in [System] Config Not Taking Effect

### ISSUE THREAD

**Issue by bwx0** [geezacoleman/OpenWeedLocator#158]
### Description
It seems that OWL is not reading from the video file specified in the `input_file_or_directory` field under the `[System]` section of the configuration file.

It looks like this behavior might be due to a missing `else` statement on [line 293](https://github.com/geezacoleman/OpenWeedLocator/blob/5045625d6da45e96513e48a6e744b3da1d11e82a/owl.py#L293) of `owl.py`.

### Steps to Reproduce
1. Set the `input_file_or_directory` field e.g. `../videos/example.mp4`
2. Run the OWL script. `python owl.py --show-display`
3. Observe that the video file is not being processed as expected. Instead, it is reading from the camera.

### Suggested Fix
Add an `else:` statement on line 293 in `owl.py` as mentioned above.

**Comment by geezacoleman** [comment]
Good find! Thanks for working this out - there are a couple of other changes I'm making to make the code more readable/robust/better at catching errors when setting everything up so I should have it updated by early next week.

You can follow the progress on the branch assigned below.
