### ISSUE TITLE
Solenoid That suit your mount STL

### ISSUE THREAD

**Issue by plains203** [geezacoleman/OpenWeedLocator#2]
Wondering if you can share what solenoids your mount was made for? I am not sure where to start looking for a suitable solenoid.

**Comment by DaleKirby** [comment]
[OWL spray parts SprayerBarn.pdf](https://github.com/geezacoleman/OpenWeedLocator/files/7080213/OWL.spray.parts.SprayerBarn.pdf)
Here's the parts list we used from sprayerbarn @plains203 @geezacoleman

**Comment by plains203** [comment]
Thanks. I had come across the Chemsaver Check Valve and Teejet body combo but the pictures of the setup you had, things looked more compact and neater.
