### ISSUE TITLE
ssh login

### ISSUE THREAD

**Issue by Surbyte** [geezacoleman/OpenWeedLocator#30]
I downloaded owl.img.
I added a ssh file to get remote access. 
Used pi as user but raspberry isn´t the right password.
Could somene help me?

**Comment by geezacoleman** [comment]
No worries! Were you able to sort it out?

**Comment by ahogan27** [comment]
Hi @geezacoleman, touching back on a SSH question. With the quick software setup procedure, what is the password for the ‘pi’ username you’ve created - so that I can login via SSH? This may not be the right forum for you to post, so fee free to message me directly if so.

**Comment by geezacoleman** [comment]
Thanks Angus! I'll add to the documentation that the password is the default.

@williamtsalter fyi - the password issue is all sorted.
