### ISSUE TITLE
Upgraded, low-cost camera for reduced image blur

### ISSUE THREAD

**Issue by geezacoleman** [geezacoleman/OpenWeedLocator#6]
Current Raspberry Pi HQ camera is good for slow speed, but becomes blurry under speeds over 8-9 kmh. Any suggestions of relatively low-cost but high quality cameras that are compatible with the RPi would be very welcome.

**Comment by plains203** [comment]
https://www.raspberrypi.org/forums/viewtopic.php?t=278195 this link may be of interest. 

Something like this might be worth looking at. Not sure what resolution you need. 
https://www.arducam.com/product/arducam-full-hd-color-global-shutter-camera-for-raspberry-pi-2-3mp-ar0234-wide-angle-pivariety-camera-module-b0353/

**Comment by geezacoleman** [comment]
That's very handy - thanks for the suggestion. We're currently dropping the resolution down to 416 x 320 anyway, so the 3MP could work. We did have some issues with drivers for the arducam previously, but not something that's impossible to overcome if it fixes the issue.

**Comment by benboughton1** [comment]
When looking at the project I was surprised it worked at all with a rolling shutter on a moving platform!

I have played around with Arducam very early on but back then it required USB connectivity. Seeing now they link direct to the camera port and use hardware functions of pi is encouraging. 

I look forward to hearing if there will be a global shutter camera selected for this project.
