### ISSUE TITLE
Changing detection settings

### ISSUE THREAD

**Issue by manninb** [geezacoleman/OpenWeedLocator#67]
For the technically incompetent like me can you step me through the following instructions on changing detection settings. I’m not sure how to open the  greenonbrown.py.

“Navigate to the owl directory and open up greenonbrown.py in an editor. You'll need to right click, select open with and then choose an integrated development environment (IDE). Once it's open, scroll down to the very bottom and you should come across:”

**Comment by geezacoleman** [comment]
How did you go with this @manninb? Were you able to change the detection settings?
