### ISSUE TITLE
generate ROS nodes for OWL

### ISSUE THREAD

**Issue by geezacoleman** [geezacoleman/OpenWeedLocator#9]
Improve cross compatibility with the fairly widely accepted standard for ag robotics. I'm very unfamiliar with ROS (though really should be better!), so this is a good project if someone wants to take it on.

**Comment by geezacoleman** [comment]
Using ROS nodes for the OWL would be a big improvement in functionality, modularity and repeatability, but could throw [some issues with Raspbian vs. Ubuntu](https://roboticsbackend.com/using-ros-on-raspberry-pi-best-practices/).

Will continue looking into it and changing the system over.

**Comment by EchelonMirror** [comment]
We can have a chat about this in a couple of months and see how we can help with a ROS2 port (ROS2 is a heck of a lot better).

**Comment by geezacoleman** [comment]
That would be great - let me know how it goes and if you have any questions. The main objective would be to allow OWL to be better integrated with field robots instead of just running as a simple python script.

**Comment by RtJinxuWang** [comment]
> That would be great - let me know how it goes and if you have any questions. The main objective would be to allow OWL to be better integrated with field robots instead of just running as a simple python script.

Sorry, I was busy with my own precise spraying project some time ago, so I rewrote a system based on ros by myself. I currently only have an nvidia device. When I have time later, I will try to encapsulate OWL into ros on an nvidia device. Besides, I have relatively little knowledge about hardware. I would like to ask you, for example, what types of cameras do the precision spraying company bilberry in France and John Deere's see and spray use? I'm currently using an industrial camera, but it's too severely affected by light!

**Comment by EchelonMirror** [comment]
What light issues are you having you having with the industrial camera?

**Comment by RtJinxuWang** [comment]
> What light issues are you having you having with the industrial camera?

![Image](https://github.com/user-attachments/assets/ef50a99c-5e7b-4263-8252-a9b36e3d7a6a)
This picture has a particularly poor imaging effect in the shadow state

**Comment by geezacoleman** [comment]
> Sorry, I was busy with my own precise spraying project some time ago, so I rewrote a system based on ros by myself. I currently only have an nvidia device. When I have time later, I will try to encapsulate OWL into ros on an nvidia device. Besides, I have relatively little knowledge about hardware. I would like to ask you, for example, what types of cameras do the precision spraying company bilberry in France and John Deere's see and spray use? I'm currently using an industrial camera, but it's too severely affected by light!

That's awesome - would be nice to see OWL on an NVIDIA device with ROS. Let me know how you go.

I'm unsure of the specifics of the hardware those companies use, and they unfortunately don't like to share and I also haven't had the opportunity to pull one apart! For research we have used FLIR Blackfly and LucidVision TritonS machine vision cameras. All struggle with harsh shadows unfortunately, which is why many companies invest in strobe or LED lighting.

The image above though, the information in the shadows is still there, so training a model on the image would likely still work quite well, it would just need data from images with shadows.

![Image](https://github.com/user-attachments/assets/8d8d0fd3-8e54-43c2-8aa9-06cbe275cd63)
