### ISSUE TITLE
Meesage for Guy Coleman

### ISSUE THREAD

**Issue by manninb** [geezacoleman/OpenWeedLocator#95]
Hi Guy,
Just so you know, I'm doing a small presentation at the Weeds Conference in Dubbo on our experiences with the OWL. Let us know if you want any input.

**Comment by geezacoleman** [comment]
Hi Bill,

I've emailed you about this a couple of times to william.manning[at]lls.nsw.gov.au - happy to contribute slides/info/background, just let me know how.
